"""your message

Revision ID: b1fc159c6fcc
Revises: dfea4d3e2144
Create Date: 2024-07-20 00:27:48.989466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fc159c6fcc'
down_revision = 'dfea4d3e2144'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
