"""your message

Revision ID: dfea4d3e2144
Revises: 8d9284ff6c3b
Create Date: 2024-04-11 23:52:42.417944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfea4d3e2144'
down_revision = '8d9284ff6c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
